import React from "react";
import ReactDOM from "react-dom";
import "bootstrap/dist/css/bootstrap.min.css";

function HomePage(){
    return(
        <div className="row">
            <p>Lorem Ipsum
          "Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..."
          "There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain..."
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ultricies lorem nibh, quis efficitur libero ultricies in. Vivamus at euismod nunc. Phasellus ullamcorper rutrum urna. In auctor augue lectus, quis convallis turpis mollis vel. Aenean mattis fringilla facilisis. Praesent ut elit non odio sodales sollicitudin a quis mi. In tincidunt metus urna, egestas luctus nisl dignissim sit amet. Donec vitae sem sem.
          Praesent ac nisi vehicula, rhoncus libero eu, feugiat dui. Proin ac ligula luctus, pretium elit eget, fermentum orci. Morbi fringilla maximus eros non euismod. Maecenas in luctus elit. Nullam euismod, tortor vel porta auctor, arcu nisi consequat tortor, in pulvinar orci odio et justo. Maecenas a sollicitudin neque, eget sollicitudin quam. Pellentesque efficitur velit eget auctor vehicula. Aenean lobortis luctus maximus. Nam at porttitor diam, vitae posuere sapien. Vivamus gravida congue nisl quis aliquam. Cras semper mattis eros. Nam eleifend tristique nisi sed iaculis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce porta est sapien, sit amet efficitur est sollicitudin non.
          Mauris elementum ex sit amet risus lobortis semper. Curabitur finibus, leo quis ultrices fringilla, ligula enim tincidunt mi, at pulvinar quam nunc at est. Cras erat est, dapibus at malesuada a, dapibus eu diam. Maecenas tincidunt dictum ligula, ultricies fermentum mauris. Integer massa magna, semper sed augue sit amet, fringilla varius nunc. Proin vel auctor dolor. Donec tincidunt justo magna, non volutpat mauris consequat vel. Etiam eleifend pretium justo eget rhoncus. Maecenas vestibulum elit nec justo tincidunt, id sollicitudin velit porttitor. Mauris justo turpis, tempus sit amet elit ut, consequat accumsan felis. Proin sit amet turpis sit amet mauris semper consequat. Fusce volutpat urna sit amet lobortis viverra. Integer aliquet facilisis elementum. Proin aliquet sed elit eu rhoncus.
          Nam laoreet non magna vel posuere. Fusce elit nulla, interdum quis varius quis, condimentum in eros. Aenean nec molestie diam. Duis ligula odio, dictum a iaculis ut, mollis ut nisl. In vitae commodo dui. Donec commodo, nunc a pellentesque fermentum, tortor odio pellentesque nulla, vitae vestibulum est lacus at elit. Cras facilisis vitae nunc quis egestas. Etiam sagittis nec nibh sed auctor. Pellentesque consectetur rutrum justo nec ultricies. Vivamus consectetur malesuada dapibus. Aenean lobortis nulla at diam euismod, commodo imperdiet sapien consequat. Donec sem nisl, gravida in dui non, imperdiet vulputate quam. Aliquam finibus augue orci. Vestibulum faucibus ultricies ante, in pellentesque eros euismod in. Nullam volutpat quis metus et consectetur. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.
          Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas commodo est vitae lectus euismod facilisis. Vivamus commodo sed lorem non varius. Fusce lectus turpis, scelerisque ut vehicula id, maximus quis nulla. Maecenas quis sapien egestas, mattis mi ac, hendrerit quam. Nulla sit amet consequat erat. Pellentesque malesuada ligula lectus, sagittis ultricies sapien mattis sit amet. Proin commodo, est vitae lacinia tristique, nunc odio varius odio, ac ullamcorper turpis massa vel nunc. Quisque eget ex non elit elementum vestibulum. Integer consectetur, diam a finibus aliquet, erat felis tincidunt purus, in porttitor risus lorem ac augue.</p>
        </div>
    );
}

export default HomePage